import turtle
import time
turtle.pencolor("black")
turtle.pensize(10)
turtle.fillcolor("green")
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()

turtle.fillcolor("yellow")
turtle.penup()
turtle.begin_fill()
turtle.goto(0,0)
turtle.pendown()
turtle.circle(-50)
turtle.end_fill()

turtle.penup()
turtle.goto(-50,-50)
turtle.seth(145)
turtle.pendown()
turtle.fd(100)

turtle.penup()
turtle.goto(50,-50)
turtle.seth(45)
turtle.pendown()
turtle.fd(100)

turtle.penup()
turtle.goto(-25,-75)
turtle.seth(-125)
turtle.pendown()
turtle.fd(200)

turtle.penup()
turtle.goto(25,-75)
turtle.seth(-55)
turtle.pendown()
turtle.fd(200)
turtle.done()
